# Generated by Django 4.1 on 2022-08-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Libro",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=100, verbose_name="titulo")),
                (
                    "imagen",
                    models.ImageField(
                        null=True, upload_to="imagenes/", verbose_name="Imagen"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(null=True, verbose_name="Descripcion"),
                ),
            ],
        ),
    ]
